export default [
    { 
        "_id": "1", 
        "title": "Quiz 1",
        "description": "Description for Quiz 1", 
        "points": 10, 
        "course": "RS101", 
        "quizType": "GRADED", 
        "assignmentGroup": "EXAMS", 
        "shuffleAnswers": true, 
        "dueDate": new Date("2026-02-10T23:59:00"),
        "availableFrom": new Date("2026-02-01T00:00:00"),
        "availableUntil": new Date("2026-02-10T23:59:00"),
        "timeLimitMinutes": 30,
        "multipleAttemptsAllowed": true,
        "numberOfAttemptsAllowed": 3,
        "showCorrectAnswers": "AFTER DUE DATE",
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webCamRequired": false,
        "lockQuestionsAfterAnswering": false,

    },
    {
        "_id": "3", 
        "title": "Car Quiz",
        "description": "Quiz on cars", 
        "points": 10, 
        "course": "RS102", 
        "quizType": "GRADED", 
        "assignmentGroup": "EXAMS", 
        "shuffleAnswers": true, 
        "dueDate": new Date("2026-02-10T23:59:00"),
        "availableFrom": new Date("2026-02-01T00:00:00"),
        "availableUntil": new Date("2026-02-10T23:59:00"),
        "timeLimitMinutes": 30,
        "multipleAttemptsAllowed": true,
        "numberOfAttemptsAllowed": 3,
        "showCorrectAnswers": "AFTER DUE DATE",
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webCamRequired": false,
        "lockQuestionsAfterAnswering": false,

    },
]